class User < ApplicationRecord
  # extends ...................................................................
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    admin: 1,      # 最高權限管理員
    client: 2,     # 客戶
  }
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :user_blog_interfaces
  has_many :blogs, through: :user_blog_interfaces

  accepts_nested_attributes_for :blogs
  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  attribute :role, :integer, default: 2
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
